name: Docker-Downloader
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo docker image prune -a -f
      - name: Pull and Save
        run: |
          docker pull hccz95/mattersim:all
          docker save hccz95/mattersim:all | gzip | split -b 2G - mattersim_all.tar.gz.
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mattersim-parts
          path: mattersim_all.tar.gz.*
          retention-days: 1
